[project]
name = "timespent"
version = "0.1.0"
description = "A web app for tracking time spent on tasks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=2.0.0",
    "flask-sqlalchemy>=3.0.0",
    "python-dotenv>=1.0.0"
]
